### ISSUE TITLE
move version.org.eap to test

### ISSUE THREAD

**Issue by jmesnil** [jfdenise/eap-maven-plugin#1]
We need to make it very clear that the eap-maven-plugin does not have a compile dependencies on any version of EAP.

afaik, this version is only used by the tests. We should move it to the tests/pom.xml to avoid any confusion (and maybe at some point, we will be able to remove it and configure it directly in the CI tests)

https://github.com/jfdenise/eap-maven-plugin/blob/0a8cff133815749164b2f40b5d2f5c174aef579d/pom.xml#L47

**Comment by jfdenise** [comment]
Thanks, fixed.
